version: '3'

services:
  app:
    build: .
    container_name: runners-application
    ports:
      - 8080:8080
      - 5005:5005 #remote debug
    depends_on:
      - mysql
    volumes:
      - ./cypress/cookies/:/usr/local/runners/cookies/
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/main/webapp/uploads/:/usr/local/runners/uploads/ # files written on local docker will end up in local the app's uploads folder which is excluded from the war
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - JAVA_TOOL_OPTIONS= -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    command: ./wait-for-it.sh mysql-standalone:3306 -t 60 -- catalina.sh run

  mysql:
    container_name: mysql-standalone
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Need to reset volume to give mysql new passwords
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - my-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
    ports:
      - "8081:80"

volumes:
  my-datavolume:

