version: '3'

services:
  app:
    build: .
    container_name: runners-application
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: ./wait-for-it.sh mysql-standalone:3306 -t 60 -- catalina.sh run

  mysql:
    container_name: mysql-standalone
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Need to reset volume to give mysql new passwords
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - my-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
    ports:
      - "8081:80"

volumes:
  my-datavolume:
